services:
  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ports:
      - '${PORT:-3000}:3000'

    environment:
      APP_JWT_SECRET: ${APP_JWT_SECRET:-}
      APP_USERS: ${APP_USERS:-}
      ACTUAL_SERVER_URL: ${ACTUAL_SERVER_URL:-}
      ACTUAL_SERVER_PASSWORD: ${ACTUAL_SERVER_PASSWORD:-}
      ACTUAL_SERVER_FILE_PASSWORD: ${ACTUAL_SERVER_FILE_PASSWORD:-}
      ACTUAL_SERVER_SYNC_ID: ${ACTUAL_SERVER_SYNC_ID:-}
      ACTUAL_SERVER_ALLOWED_ACCOUNTS: ${ACTUAL_SERVER_ALLOWED_ACCOUNTS:-*}

    restart: no
